export default{

    USR001:'Invalid First Name',
    USR002:'Invalid Last Name',
    USR003:'Invalid Username',
    USR004:'Invalid IP Address',
    USR005:'Invalid Password',
    USR006:'Invalid Email Id',
    USR007:'Duplicate Username',
    USR008:'Duplicate Facebook Id',
    USR009:'Invalid FacebookId',
    USR010:'Invalid Facebook Token',
    USR011:'Invalid Profile id',
    USR012:'invalid Push notification token',
    USR013:'User created successfully',
    USR014:'Login Successful',
    USR015:'User reterived successfully',
    USR016:'Error creating token for user',
    USR017:'Duplicate email address',
    USR018:'Error creating user balance',
    USR019:'Player id missing',
    USR020:'User reterived',
    USR021:'Invalid parameters for update',
    USR022:'Error Generating OTP',
    USR023:'Duplicate phone no',
    USR024:'user  blocked',
    USR025:'phone not verified',
    USR026:'invalid otp',
    USR027:'otp verified',
    USR404:'User not found',
    USR100:'Unspecified user error',
    USR101:'User token expired',
    USR028:'User already verified',
    USR029:'OTP regenerated',
    USR030:'insufficient balance'
    
}